"""
BI Agent Service for Monday.com BI Agent.
Interacts with the Groq API through the official OpenAI-compatible Python client to answer executive
business questions and generate leadership reports based strictly on
pre-computed business metrics from analytics_engine.py.

This module NEVER calculates business KPIs directly.
"""

from datetime import datetime, timezone
import json
import logging
import os
from typing import Any

from dotenv import load_dotenv
from openai import OpenAI
import pandas as pd

# Load environment variables
load_dotenv()

# Logger configuration
logger = logging.getLogger(__name__)

# Import generate_dashboard_metrics without calculation duplication
try:
    from services.analytics_engine import generate_dashboard_metrics
except ImportError:
    from backend.services.analytics_engine import generate_dashboard_metrics


class BIAgent:
    """
    AI Business Intelligence Agent advising executives and founders.
    Uses Groq-hosted models to interpret analytics_engine KPIs.
    """

    DEFAULT_MODEL = "openai/gpt-oss-120b"

    def __init__(self, api_key: str | None = None, model: str | None = None):
        """
        Initialize the BI Agent with Groq's OpenAI-compatible API.

        Args:
            api_key: Optional Groq API key. If not provided, it is loaded
                     from the GROQ_API_KEY environment variable.
            model: Optional Groq model identifier. If not provided, it is loaded
                   from GROQ_MODEL or defaults to Groq's production GPT-OSS 120B model.

        Raises:
            ValueError: If GROQ_API_KEY is not set or provided.
        """
        self.api_key = api_key or os.getenv("GROQ_API_KEY")
        if not self.api_key:
            raise ValueError(
                "GROQ_API_KEY environment variable is not set and no API key was provided."
            )

        self.client = OpenAI(
            api_key=self.api_key,
            base_url="https://api.groq.com/openai/v1",
        )
        self.model = self._resolve_model(model)
        logger.info("BIAgent initialized successfully with Groq model '%s'.", self.model)

    def _resolve_model(self, requested_model: str | None = None) -> str:
        """
        Resolve the configured Groq model without provider-side model discovery.
        """
        if requested_model and requested_model.strip():
            return requested_model.strip()

        env_model = os.getenv("GROQ_MODEL")
        if env_model and env_model.strip():
            return env_model.strip()

        return self.DEFAULT_MODEL

    def _generate_content_with_fallback(self, prompt: str) -> Any:
        """
        Generate content using Groq's OpenAI-compatible Chat Completions API.
        """
        logger.info("Calling Groq Chat Completions with model: '%s'", self.model)
        return self.client.chat.completions.create(
            model=self.model,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.2,
        )

    def _build_context(
        self,
        dashboard_metrics: dict[str, Any],
        quality_report: dict[str, Any] | None = None,
    ) -> str:
        """
        Build a structured, readable context string from pre-computed metrics
        and quality caveats for the LLM prompt.

        Args:
            dashboard_metrics: Dictionary generated by analytics_engine.generate_dashboard_metrics().
            quality_report: Optional data quality report dictionary.

        Returns:
            str: Formatted context text string.
        """
        caveats = []
        if quality_report and isinstance(quality_report, dict):
            caveats = quality_report.get("caveats", [])

        context_blocks = [
            "=== BUSINESS ANALYTICS METRICS CONTEXT ===",
            f"Pipeline Summary:\n{json.dumps(dashboard_metrics.get('pipeline_summary', {}), indent=2)}",
            f"Revenue by Sector:\n{json.dumps(dashboard_metrics.get('revenue_by_sector', {}), indent=2)}",
            f"Revenue by Stage:\n{json.dumps(dashboard_metrics.get('revenue_by_stage', {}), indent=2)}",
            f"Monthly Pipeline:\n{json.dumps(dashboard_metrics.get('monthly_pipeline', {}), indent=2)}",
            f"Work Order Summary:\n{json.dumps(dashboard_metrics.get('work_order_summary', {}), indent=2)}",
            f"Billing Summary:\n{json.dumps(dashboard_metrics.get('billing_summary', {}), indent=2)}",
            f"Top Customers:\n{json.dumps(dashboard_metrics.get('top_customers', []), indent=2)}",
            f"Execution Metrics:\n{json.dumps(dashboard_metrics.get('execution_metrics', {}), indent=2)}",
            f"Data Quality Caveats:\n{json.dumps(caveats, indent=2)}",
        ]

        return "\n\n".join(context_blocks)

    def _extract_response_text(self, response: Any) -> str | None:
        """
        Safely extract text content from an OpenAI-compatible chat completion.

        Args:
            response: Response object returned by client.chat.completions.create().

        Returns:
            str | None: Cleaned text string or None if unavailable.
        """
        if not response:
            return None

        # 1. Attempt the standard OpenAI-compatible response shape.
        try:
            choices = getattr(response, "choices", None)
            text = choices[0].message.content if choices else None
            if text and text.strip():
                return text.strip()
        except Exception as e:
            logger.warning("Standard chat completion content access threw warning/error: %s", e)

        return None

    def answer_question(
        self,
        question: str,
        deals_df: pd.DataFrame,
        wo_df: pd.DataFrame,
        quality_report: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """
        Answer strategic business question from executive users based on metrics.

        Args:
            question: The user's executive question.
            deals_df: Cleaned Deals DataFrame.
            wo_df: Cleaned Work Orders DataFrame.
            quality_report: Optional quality report dictionary.

        Returns:
            dict: Structured response containing answer text, dashboard metrics, and caveats.
        """
        logger.info("BIAgent processing user question: '%s'", question)

        # 1. Fetch pre-computed metrics from analytics_engine (NEVER recalculate here)
        dashboard_metrics = generate_dashboard_metrics(deals_df, wo_df)
        notes = quality_report.get("caveats", []) if quality_report else []

        # 2. Construct LLM context prompt
        context_str = self._build_context(dashboard_metrics, quality_report)

        system_prompt = (
            "You are a senior Business Intelligence analyst advising founders and executives. "
            "Your objective is to answer strategic business questions accurately using ONLY the "
            "provided pre-computed analytics context.\n\n"
            "Guidelines:\n"
            "1. Explain strategic reasoning clearly and concisely.\n"
            "2. Highlight trends, growth drivers, operational risks, and key commercial opportunities.\n"
            "3. Explicitly reference specific numeric metrics from the context.\n"
            "4. Mention relevant data quality caveats when pertinent to the question.\n"
            "5. NEVER invent, fabricate, or extrapolate numbers not explicitly present in the metrics.\n"
            "6. If the user's question is ambiguous, provide a high-level answer first and then ask ONE concise clarifying question."
        )

        full_prompt = (
            f"{system_prompt}\n\n"
            f"EXECUTIVE QUESTION:\n{question}\n\n"
            f"ANALYTICS METRICS CONTEXT:\n{context_str}\n\n"
            "Please provide your professional analysis:"
        )

        # 3. Request content generation from Groq.
        answer_text = None
        try:
            response = self._generate_content_with_fallback(full_prompt)
            answer_text = self._extract_response_text(response)
            if answer_text:
                logger.info("Successfully generated Groq AI response for user question.")
            else:
                logger.warning("Groq API returned an empty response.")
                answer_text = (
                    "The AI response was unavailable or blocked by safety filters. "
                    "Please rephrase your question or consult the executive dashboard metrics directly."
                )

        except Exception as e:
            err_msg = str(e)
            if "429" in err_msg or "quota" in err_msg.lower():
                logger.warning("Groq API quota or rate limit exceeded: %s", e)
                answer_text = "The AI service has reached its usage quota. Please try again later."
            else:
                logger.error("Error calling Groq API in BIAgent.answer_question: %s", e, exc_info=True)
                answer_text = "AI Service Error: Unable to complete request with Groq API. Please try again later."

        return {
            "answer": answer_text,
            "dashboard_metrics": dashboard_metrics,
            "data_quality_notes": notes,
        }

    def generate_leadership_report(
        self,
        deals_df: pd.DataFrame,
        wo_df: pd.DataFrame,
        quality_report: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """
        Generate a comprehensive executive leadership report formatted in Markdown.

        Args:
            deals_df: Cleaned Deals DataFrame.
            wo_df: Cleaned Work Orders DataFrame.
            quality_report: Optional quality report dictionary.

        Returns:
            dict: Dictionary containing Markdown report text and timestamp.
        """
        logger.info("BIAgent generating executive leadership report.")

        # 1. Fetch pre-computed metrics
        dashboard_metrics = generate_dashboard_metrics(deals_df, wo_df)
        context_str = self._build_context(dashboard_metrics, quality_report)

        system_prompt = (
            "You are a Chief Business Officer preparing an executive leadership report for "
            "founders and board members based on company metrics.\n\n"
            "CRITICAL INSTRUCTION:\n"
            "Your response MUST be formatted in Markdown and MUST contain the following EXACT header sections:\n\n"
            "# Executive Summary\n\n"
            "# Sales Pipeline Health\n\n"
            "# Revenue Insights\n\n"
            "# Operational Performance\n\n"
            "# Billing Overview\n\n"
            "# Key Risks\n\n"
            "# Recommended Actions\n\n"
            "# Data Quality Notes\n\n"
            "Guidelines:\n"
            "- Ground every insight strictly in the provided numeric metrics.\n"
            "- Make recommendations practical, high-impact, and directly tied to metrics.\n"
            "- Do not fabricate numbers or speculate beyond the data."
        )

        full_prompt = (
            f"{system_prompt}\n\n"
            f"Generate a comprehensive executive leadership report based on this metrics context:\n\n"
            f"{context_str}"
        )

        report_text = None
        try:
            response = self._generate_content_with_fallback(full_prompt)
            report_text = self._extract_response_text(response)
            if report_text:
                logger.info("Successfully generated executive leadership report with Groq API.")
            else:
                logger.warning("Groq API returned an empty report response.")
                report_text = (
                    "# Executive Leadership Report\n\n"
                    "*The report generation response was empty or blocked by safety filters. "
                    "Please try again or refer to the pre-computed metrics dashboard.*"
                )

        except Exception as e:
            err_msg = str(e)
            if "429" in err_msg or "quota" in err_msg.lower():
                logger.warning("Groq API quota or rate limit exceeded: %s", e)
                report_text = (
                    "# Executive Leadership Report\n\n"
                    "The AI service has reached its usage quota. Please try again later."
                )
            else:
                logger.error("Error generating leadership report with Groq API: %s", e, exc_info=True)
                report_text = (
                    "# Executive Report Generation Error\n\n"
                    "AI Service Error: Unable to complete request with Groq API. Please try again later."
                )

        iso_now = datetime.now(timezone.utc).isoformat()
        return {
            "report": report_text,
            "generated_at": iso_now,
        }
