"""
BI Agent Service for Monday.com BI Agent.
Interacts with Google Gemini API using google-genai SDK to answer executive
business questions and generate leadership reports based strictly on
pre-computed business metrics from analytics_engine.py.

This module NEVER calculates business KPIs directly.
"""

from datetime import datetime, timezone
import json
import logging
import os
from typing import Any

from dotenv import load_dotenv
from google import genai
import pandas as pd

# Load environment variables
load_dotenv()

# Logger configuration
logger = logging.getLogger(__name__)

# Import generate_dashboard_metrics without calculation duplication
try:
    from services.analytics_engine import generate_dashboard_metrics
except ImportError:
    from backend.services.analytics_engine import generate_dashboard_metrics


class BIAgent:
    """
    AI Business Intelligence Agent advising executives and founders.
    Uses Google Gemini models to interpret analytics_engine KPIs.
    """

    DEFAULT_MODEL = "gemini-2.5-flash"

    def __init__(self, api_key: str | None = None, model: str = DEFAULT_MODEL):
        """
        Initialize the BI Agent with Google GenAI SDK.

        Args:
            api_key: Optional Gemini API key. If not provided, it is loaded
                     from the GEMINI_API_KEY environment variable.
            model: Gemini model identifier to use (defaults to 'gemini-2.5-flash').

        Raises:
            ValueError: If GEMINI_API_KEY is not set or provided.
        """
        self.api_key = api_key or os.getenv("GEMINI_API_KEY")
        if not self.api_key:
            raise ValueError(
                "GEMINI_API_KEY environment variable is not set and no API key was provided."
            )

        self.model = model
        self.client = genai.Client(api_key=self.api_key)
        logger.info("BIAgent initialized successfully with model '%s'.", self.model)

    def _build_context(
        self,
        dashboard_metrics: dict[str, Any],
        quality_report: dict[str, Any] | None = None,
    ) -> str:
        """
        Build a structured, readable context string from pre-computed metrics
        and quality caveats for the LLM prompt.

        Args:
            dashboard_metrics: Dictionary generated by analytics_engine.generate_dashboard_metrics().
            quality_report: Optional data quality report dictionary.

        Returns:
            str: Formatted context text string.
        """
        caveats = []
        if quality_report and isinstance(quality_report, dict):
            caveats = quality_report.get("caveats", [])

        context_blocks = [
            "=== BUSINESS ANALYTICS METRICS CONTEXT ===",
            f"Pipeline Summary:\n{json.dumps(dashboard_metrics.get('pipeline_summary', {}), indent=2)}",
            f"Revenue by Sector:\n{json.dumps(dashboard_metrics.get('revenue_by_sector', {}), indent=2)}",
            f"Revenue by Stage:\n{json.dumps(dashboard_metrics.get('revenue_by_stage', {}), indent=2)}",
            f"Monthly Pipeline:\n{json.dumps(dashboard_metrics.get('monthly_pipeline', {}), indent=2)}",
            f"Work Order Summary:\n{json.dumps(dashboard_metrics.get('work_order_summary', {}), indent=2)}",
            f"Billing Summary:\n{json.dumps(dashboard_metrics.get('billing_summary', {}), indent=2)}",
            f"Top Customers:\n{json.dumps(dashboard_metrics.get('top_customers', []), indent=2)}",
            f"Execution Metrics:\n{json.dumps(dashboard_metrics.get('execution_metrics', {}), indent=2)}",
            f"Data Quality Caveats:\n{json.dumps(caveats, indent=2)}",
        ]

        return "\n\n".join(context_blocks)

    def answer_question(
        self,
        question: str,
        deals_df: pd.DataFrame,
        wo_df: pd.DataFrame,
        quality_report: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """
        Answer strategic business question from executive users based on metrics.

        Args:
            question: The user's executive question.
            deals_df: Cleaned Deals DataFrame.
            wo_df: Cleaned Work Orders DataFrame.
            quality_report: Optional quality report dictionary.

        Returns:
            dict: Structured response containing answer text, dashboard metrics, and caveats.
        """
        logger.info("BIAgent processing user question: '%s'", question)

        # 1. Fetch pre-computed metrics from analytics_engine (NEVER recalculate here)
        dashboard_metrics = generate_dashboard_metrics(deals_df, wo_df)
        notes = quality_report.get("caveats", []) if quality_report else []

        # 2. Construct LLM context prompt
        context_str = self._build_context(dashboard_metrics, quality_report)

        system_prompt = (
            "You are a senior Business Intelligence analyst advising founders and executives. "
            "Your objective is to answer strategic business questions accurately using ONLY the "
            "provided pre-computed analytics context.\n\n"
            "Guidelines:\n"
            "1. Explain strategic reasoning clearly and concisely.\n"
            "2. Highlight trends, growth drivers, operational risks, and key commercial opportunities.\n"
            "3. Explicitly reference specific numeric metrics from the context.\n"
            "4. Mention relevant data quality caveats when pertinent to the question.\n"
            "5. NEVER invent, fabricate, or extrapolate numbers not explicitly present in the metrics.\n"
            "6. If the user's question is ambiguous, provide a high-level answer first and then ask ONE concise clarifying question."
        )

        full_prompt = (
            f"{system_prompt}\n\n"
            f"EXECUTIVE QUESTION:\n{question}\n\n"
            f"ANALYTICS METRICS CONTEXT:\n{context_str}\n\n"
            "Please provide your professional analysis:"
        )

        # 3. Request content generation from Google Gemini API with error handling
        try:
            response = self.client.models.generate_content(
                model=self.model,
                contents=full_prompt,
            )
            answer_text = response.text or ""
            logger.info("Successfully generated Gemini AI response for user question.")

        except Exception as e:
            logger.exception("Error calling Gemini API in BIAgent.answer_question: %s", e)
            answer_text = f"AI Service Error: Gemini API returned an error ({e})."

        return {
            "answer": answer_text,
            "dashboard_metrics": dashboard_metrics,
            "data_quality_notes": notes,
        }

    def generate_leadership_report(
        self,
        deals_df: pd.DataFrame,
        wo_df: pd.DataFrame,
        quality_report: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """
        Generate a comprehensive executive leadership report formatted in Markdown.

        Args:
            deals_df: Cleaned Deals DataFrame.
            wo_df: Cleaned Work Orders DataFrame.
            quality_report: Optional quality report dictionary.

        Returns:
            dict: Dictionary containing Markdown report text and timestamp.
        """
        logger.info("BIAgent generating executive leadership report.")

        # 1. Fetch pre-computed metrics
        dashboard_metrics = generate_dashboard_metrics(deals_df, wo_df)
        context_str = self._build_context(dashboard_metrics, quality_report)

        system_prompt = (
            "You are a Chief Business Officer preparing an executive leadership report for "
            "founders and board members based on company metrics.\n\n"
            "CRITICAL INSTRUCTION:\n"
            "Your response MUST be formatted in Markdown and MUST contain the following EXACT header sections:\n\n"
            "# Executive Summary\n\n"
            "# Sales Pipeline Health\n\n"
            "# Revenue Insights\n\n"
            "# Operational Performance\n\n"
            "# Billing Overview\n\n"
            "# Key Risks\n\n"
            "# Recommended Actions\n\n"
            "# Data Quality Notes\n\n"
            "Guidelines:\n"
            "- Ground every insight strictly in the provided numeric metrics.\n"
            "- Make recommendations practical, high-impact, and directly tied to metrics.\n"
            "- Do not fabricate numbers or speculate beyond the data."
        )

        full_prompt = (
            f"{system_prompt}\n\n"
            f"Generate a comprehensive executive leadership report based on this metrics context:\n\n"
            f"{context_str}"
        )

        try:
            response = self.client.models.generate_content(
                model=self.model,
                contents=full_prompt,
            )
            report_text = response.text or ""
            logger.info("Successfully generated executive leadership report with Gemini API.")

        except Exception as e:
            logger.exception("Error generating leadership report with Gemini API: %s", e)
            report_text = f"# Executive Report Generation Error\n\nGemini API Error ({e})."

        iso_now = datetime.now(timezone.utc).isoformat()
        return {
            "report": report_text,
            "generated_at": iso_now,
        }
